// CausalGuard 顶层构建脚本
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.4.1'
        classpath 'org.jetbrains.kotlin:kotlin-serialization:2.2.10'
        classpath 'com.google.devtools.ksp:symbol-processing-gradle-plugin:2.3.4'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
